name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: update branch
      #   run: git pull

      # - name: Instalar Angular CLI
      #   run: npm install -g @angular/cli

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.13.0"

      - name: Install dependencies
        run: yarn install

      - name: Build Angular app
        run: ng build

      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@releases/v4
      #   with:
      #     branch: public-pages
      #     folder: dist/
